import img1 from '../../../img/logo.png';
const Allwork = [
	{
		id: 1,
		category: "Animation",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Explainer Video",
	},
	{
		id: 2,
		category: "Python",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Python Web Scrapping",
	},
	{
		id: 3,
		category: "Animation",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Autodesk Maya",
	},
	{
		id: 4,
		category: "Javascript",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Vanilla Javascript Website",
	},
	{
		id: 5,
		category: "React Js",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Getting Started With React",
	},
	{
		id: 6,
		category: "React Js",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Vanilla Javascript Website",
	},
	{
		id: 7,
		category: "Test Port",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Vanilla Javascript Website",
	},
	{
		id: 8,
		category: "Test Port",
		link1: "www.youtube.com",
		link2: "www.github.com",
		icon1: "G",
		icon2: "Y",
		image: img1,
		url: "https://www.youtube.com/watch?v=G9RAjvus4AY",
		title: "Vanilla Javascript Website",
	},
	
];

export default Allwork;
